export * from './Email';
export * from './PhoneNumber';
export * from './Address';
export * from './IPAddress';
export * from './MACAddress';
export * from './NetworkDeviceStatus';
export * from './NetworkDeviceType';
export * from './PollingInterval';
export * from './PollingStatus';
export * from './RetryPolicy';
export * from './PollingMetrics';
export * from './UUID';
/*export * from './WebsiteURL';*/
