export interface WirelessMetricsProps {
  signalRxDbm: number | null;
  signalTxDbm: number | null;
  noiseFloorDbm: number | null;
  snrDb: number | null;
  ccqPercent: number | null;
  txRateMbps: number | null;
  rxRateMbps: number | null;
  frequencyMhz: number | null;
  channelWidthMhz: number | null;
  txPowerDbm: number | null;
  throughputTxBps: number | null;
  throughputRxBps: number | null;
  lanStatus: 'UP' | 'DOWN' | null;
  lanSpeedMbps: number | null;
  lanDuplex: 'FULL' | 'HALF' | null;
  uptimeSeconds: number | null;
  cpuLoadPercent: number | null;
  memoryUsedPercent: number | null;
  clientsConnected: number | null;
  clientsProvisioned: number | null;
  throughputTxPps: number | null;
  throughputRxPps: number | null;
  firmwareVersion: string | null;
  deviceName: string | null;
  remoteApMac: string | null;
  remoteApName: string | null;
  distanceM: number | null;
  latencyMs: number | null;
}
