export * from './PrismaLocationRepository';
export * from './PrismaDeviceRepository';
export * from './PrismaDeviceModelRepository';
export * from './PrismaVendorRepository';
export * from './PrismaPollingConfigurationRepository';
export * from './PrismaPingResultRepository';
export * from './PrismaDeviceStateRepository';
export * from './PrismaDeviceCredentialsRepository';
export * from './PrismaAlertRepository';
