export enum LocationType {
  TOWER = 'TOWER',
  DATACENTER = 'DATACENTER',
  POINT_OF_PRESENCE = 'POINT_OF_PRESENCE',
  OFFICE = 'OFFICE',
  CUSTOMER_PREMISES = 'CUSTOMER_PREMISES',
  OTHER = 'OTHER'
}
