export enum LocationType {
  TOWER = 'TOWER',
  NODE = 'NODE',
  DATACENTER = 'DATACENTER',
  POP = 'POP',
  WAREHOUSE = 'WAREHOUSE',
  OFFICE = 'OFFICE',
  CUSTOMER_PREMISES = 'CUSTOMER_PREMISES',
  OTHER = 'OTHER'
}
